services:
  - docker

install:
  - docker pull jjmerelo/test-perl6
  - docker images
  - docker run -t --entrypoint="/bin/sh" jjmerelo/test-perl6 -c "apk update && apk upgrade && apk add libfftw3-double3"
  - docker run -t --entrypoint="/bin/sh" jjmerelo/test-perl6 -c "perl6 --version; which zef"

script:
- docker run -t -v  $TRAVIS_BUILD_DIR:/test jjmerelo/test-perl6
